theme: jekyll-theme-minimal
title: Alejandro N. Diaz
description: <img align="left" width="240" height="240" src="headshot_cropped.jpg" style="margin:0px 15px">

I am a Ph.D. student in the
[Department of Computational and Applied Mathematics](https://caamweb.rice.edu/)  (CAAM) at 
[Rice University](https://www.rice.edu/) in Houston, TX. My 
advisor is Prof. [Matthias Heinkenschloss](https://www.caam.rice.edu/~heinken/)
and my research focuses on data-driven model reduction for nonlinear dynamical systems. 
I am a [National Defense Science and Engineering Graduate (NDSEG) Fellow](https://ndseg.org/)
sponsored by the [Air Force Research Laboratory (AFRL)](https://www.afrl.af.mil/). 
Here is my [CV](ad_cv.pdf).
